//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayTemplatesDemo.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
public partial class Address
{
    public int ID { get; set; }
    public int UserID { get; set; }
    public string StreetAddress { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string PostalCode { get; set; }
    
    public virtual User User { get; set; }
}
}
