//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayTemplatesDemo.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Roles = new HashSet<Role>();
            this.Addresses = new HashSet<Address>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string UserName { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
